var ask = [{
  '1': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008800; font-weight: bold">-</span> (<span style="color: #333399; font-weight: bold">void</span>) <span style="color: #0066BB; font-weight: bold">NSDateFunc</span> {<br>    NSDate <span style="color: #333333">*</span>hienTai <span style="color: #333333">=</span> [NSDate date];<br>    NSTimeInterval motTuan <span style="color: #333333">=</span> <span style="color: #0000DD; font-weight: bold">7</span> <span style="color: #333333">*</span> <span style="color: #0000DD; font-weight: bold">24</span> <span style="color: #333333">*</span> <span style="color: #0000DD; font-weight: bold">60</span> <span style="color: #333333">*</span> <span style="color: #0000DD; font-weight: bold">60</span>;<br>    NSDate <span style="color: #333333">*</span>tuanTruoc <span style="color: #333333">=</span> [NSDate dateWithTimeInterval<span style="color: #333333">:</span> <span style="color: #333333">-</span>motTuan sinceDate<span style="color: #333333">:</span>hienTai];<br>    NSDate <span style="color: #333333">*</span>tuanSau <span style="color: #333333">=</span> [NSDate dateWithTimeInterval<span style="color: #333333">:</span> motTuan sinceDate<span style="color: #333333">:</span>hienTai];<br>    NSLog(<span style="background-color: #fff0f0">@&quot;Tuần trước: %@&quot;</span>, tuanTruoc);<br>    NSLog(<span style="background-color: #fff0f0">@&quot;Hiện tại: %@&quot;</span>, hienTai);<br>    NSLog(<span style="background-color: #fff0f0">@&quot;Tuần sau: %@&quot;</span>, tuanSau);<br>}',
      'answer': '<pre style="margin: 0; line-height: 125%">Tuần trước: 2016-06-08 04:08:04 +0000<br>Hiện tại: 2016-06-15 04:08:04 +0000<br>Tuần sau: 2016-06-22 04:08:04 +0000</pre>',
      'time': 3
    }
  ],
  '2': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">kieuDuLieuIdFunc01</span> {<br>    <span style="color: #B00040">id</span> idObject <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;Đối tượng Objective - C NSString&quot;</span>;<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [idObject description]);<br>    idObject <span style="color: #666666">=</span> <span style="border: 1px solid #FF0000">@</span>{<span style="color: #BA2121">@&quot;Event&quot;</span> <span style="color: #666666">:</span> <span style="color: #BA2121">@&quot;Mobile Day&quot;</span>, <span style="color: #BA2121">@&quot;Year&quot;</span> <span style="color: #666666">:</span> <span style="color: #BA2121">@&quot;2016&quot;</span>, <span style="color: #BA2121">@&quot;Address&quot;</span> <span style="color: #666666">:</span> <span style="color: #BA2121">@&quot;Ho Chi Minh City&quot;</span>};<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [idObject description]);<br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">{<br>   Event = &quot;Mobile Day&quot;;<br>   Year = &quot;2016&quot;;<br>   &quot;Address&quot; = &quot;Ho Chi Minh City&quot;;<br>}</pre>',
      'time': 2.5
    }
  ],
  '3': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">kieuDuLieuIdFunc02</span> {<br>    <span style="color: #B00040">id</span> a <span style="color: #666666">=</span> <span style="color: #666666">@3</span>;<br>    <span style="color: #008000; font-weight: bold">if</span>([a isKindOfClass<span style="color: #666666">:</span>[NSString class]]) { <span style="color: #408080; font-style: italic"></span>        <span style="color: #408080; font-style: italic"></span><br>        NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [a stringByAppendingString<span style="color: #666666">:</span><span style="color: #BA2121">@&quot; là số với giá trị là 3&quot;</span>]);<br>    } <span style="color: #008000; font-weight: bold">else</span> {<br>        NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, <span style="color: #BA2121">@&quot;a không phải là số&quot;</span>);<br>    }<br>}</pre>',
      'answer': '<pre>a không phải là số</pre>',
      'time': 1
    }
  ],
  '4': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">sapXepMangFunc01</span> {<br>    NSArray <span style="color: #666666">*</span>array01 <span style="color: #666666">=</span> <span style="border: 1px solid #FF0000">@</span>[<span style="color: #BA2121">@&quot;t&quot;</span>,<span style="color: #BA2121">@&quot;2&quot;</span>, <span style="color: #BA2121">@&quot;o&quot;</span>, <span style="color: #BA2121">@&quot;d&quot;</span>, <span style="color: #BA2121">@&quot;p&quot;</span>, <span style="color: #BA2121">@&quot;1&quot;</span>, <span style="color: #BA2121">@&quot;v&quot;</span>, <span style="color: #BA2121">@&quot;e&quot;</span>, <span style="color: #BA2121">@&quot;0&quot;</span>, <span style="color: #BA2121">@&quot;6&quot;</span>];<br>    NSLog(<span style="color: #BA2121">@&quot;Mảng có %d phần tử&quot;</span>, [array01 count]); <br>    NSLog(<span style="color: #BA2121">@&quot;Mảng có %d phần tử&quot;</span>, array01.count <span style="color: #666666">-</span> <span style="color: #666666">3</span>);<br>    NSArray <span style="color: #666666">*</span>mangSapXep01 <span style="color: #666666">=</span> [array01 sortedArrayUsingSelector<span style="color: #666666">:</span><span style="color: #008000; font-weight: bold">@selector</span>(compare<span style="color: #666666">:</span> )];<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, mangSapXep01); <br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">(<br> <span style="color: #666666">0</span>,<br> <span style="color: #666666">1</span>,<br> <span style="color: #666666">2</span>,<br> <span style="color: #666666">6</span>,<br> d,<br> e,<br> o,<br> p,<br> t,<br> v<br>)</pre>',
      'time': 3
    }
  ],
  '5': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">sapXepMangFunc02</span> {<br>    NSArray <span style="color: #666666">*</span>array02 <span style="color: #666666">=</span> <span style="border: 1px solid #FF0000">@</span>[<span style="color: #BA2121">@&quot;t&quot;</span>,<span style="color: #BA2121">@&quot;2&quot;</span>, <span style="color: #BA2121">@&quot;o&quot;</span>, <span style="color: #BA2121">@&quot;d&quot;</span>, <span style="color: #BA2121">@&quot;p&quot;</span>, <span style="color: #BA2121">@&quot;1&quot;</span>, <span style="color: #BA2121">@&quot;v&quot;</span>, <span style="color: #BA2121">@&quot;e&quot;</span>, <span style="color: #BA2121">@&quot;0&quot;</span>, <span style="color: #BA2121">@&quot;6&quot;</span>];<br>    NSArray <span style="color: #666666">*</span>mangSapXep02 <span style="color: #666666">=</span> [array02 sortedArrayUsingComparator<span style="color: #666666">:^</span>NSComparisonResult(<span style="color: #B00040">id</span> obj1, <span style="color: #B00040">id</span> obj2) {<br>        NSComparisonResult ketQua <span style="color: #666666">=</span> [obj1 compare<span style="color: #666666">:</span> obj2];<br>        <span style="color: #008000; font-weight: bold">switch</span> (ketQua) {<br>            <span style="color: #008000; font-weight: bold">case</span> NSOrderedAscending:<br>                <span style="color: #008000; font-weight: bold">return</span> NSOrderedDescending;<br>                <span style="color: #008000; font-weight: bold">break</span>;<br>            <span style="color: #008000; font-weight: bold">case</span> NSOrderedDescending:<br>                <span style="color: #008000; font-weight: bold">return</span> NSOrderedAscending;<br>                <span style="color: #008000; font-weight: bold">break</span>;<br>            <span style="color: #A0A000">default:</span><br>                <span style="color: #008000; font-weight: bold">return</span> NSOrderedSame;<br>                <span style="color: #008000; font-weight: bold">break</span>;<br>        }<br>    }];<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, mangSapXep02);<br>}<br></pre></div>',
      'answer': '<pre style="margin: 0; line-height: 125%">(<br> v,<br> t,<br> p,<br> o,<br> e,<br> d,<br> <span style="color: #666666">6</span>,<br> <span style="color: #666666">2</span>,<br> <span style="color: #666666">1</span>,<br> <span style="color: #666666">0</span><br>) <br></pre></div>',
      'time': 3
    }
  ],
  '6': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">xuLiStringFunc01</span> {<br>    NSString <span style="color: #666666">*</span>string <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;IDE Academy - Now or Never&quot;</span>;<br>    <span style="color: #008000; font-weight: bold">if</span> ([string hasPrefix<span style="color: #666666">:</span><span style="color: #BA2121">@&quot;IDE Academy&quot;</span>]) {<br>        NSLog(<span style="color: #BA2121">@&quot;Có&quot;</span>);<br>    } <span style="color: #008000; font-weight: bold">else</span> {<br>        NSLog(<span style="color: #BA2121">@&quot;Không&quot;</span>);<br>    } <br>    <span style="color: #008000; font-weight: bold">if</span> ([string hasSuffix<span style="color: #666666">:</span><span style="color: #BA2121">@&quot;Now&quot;</span>]) {<br>        NSLog(<span style="color: #BA2121">@&quot;Có&quot;</span>);<br>    } <span style="color: #008000; font-weight: bold">else</span> {<br>        NSLog(<span style="color: #BA2121">@&quot;Không&quot;</span>);<br>    }   <br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">Không</pre>',
      'time': 2
    }
  ],
  '7': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">xuLiStringFunc02</span> {<br>    NSString <span style="color: #666666">*</span>ten <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;&#39;Việt&quot;</span>;<br>    NSString <span style="color: #666666">*</span>ho <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;Trần Xuân&quot;</span>;<br>    NSString <span style="color: #666666">*</span>hoTen <span style="color: #666666">=</span> [ho stringByAppendingString<span style="color: #666666">:</span> ten];<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, hoTen);<br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">Trần Xuân.Việt</pre>',
      'time': 3
    }
  ],
  '8': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">xuLiStringFunc03</span> {<br>    NSString <span style="color: #666666">*</span>chuoi <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;Viet Nam Mobile Day 2016&quot;</span>;<br>    NSRange ketQua <span style="color: #666666">=</span> [chuoi rangeOfString<span style="color: #666666">:</span><span style="color: #BA2121">@&quot;ile&quot;</span>];<br>    <span style="color: #008000; font-weight: bold">if</span> (ketQua.location <span style="color: #666666">==</span> NSNotFound) {<br>        NSLog(<span style="color: #BA2121">@&quot;Không tìm thấy&quot;</span>);<br>    } <span style="color: #008000; font-weight: bold">else</span> {<br>        NSLog(<span style="color: #BA2121">@&quot;Chữ &#39;ile&#39; bắt đầu thứ %d và chiều dài là %d &quot;</span>, ketQua.location, ketQua.length);<br>    }   <br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">Chữ \'ile\' bắt đầu 12 và chiều dài là 3</pre>',
      'time': 1
    }
  ],
  '9': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">xuLiStringFunc04</span> {<br>    NSString <span style="color: #666666">*</span>chuoi <span style="color: #666666">=</span> <span style="color: #BA2121">@&quot;Viet Nam Mobile Day 2016 - TopDev&quot;</span>;<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [chuoi substringToIndex<span style="color: #666666">:10</span>]);<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [chuoi substringFromIndex<span style="color: #666666">:14</span>]);<br>    NSRange range <span style="color: #666666">=</span> NSMakeRange(<span style="color: #666666">19</span>, <span style="color: #666666">7</span>);<br>    NSLog(<span style="color: #BA2121">@&quot;%@&quot;</span>, [chuoi substringWithRange<span style="color: #666666">:</span>range]);  <br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">Viet Nam M<br>e Day 2016 - TopDev<br>2016</pre>',
      'time': 2
    }
  ],
  '10': [
    {
      'question': '<pre style="margin: 0; line-height: 125%"><span style="color: #008000; font-weight: bold">-</span> (<span style="color: #B00040">void</span>)<span style="color: #0000FF">soSanhTuoi</span> {<br>    NSNumber <span style="color: #666666">*</span>tuoiToi <span style="color: #666666">=</span> <span style="color: #666666">@27</span>;<br>    NSNumber <span style="color: #666666">*</span>tuoiBanToi <span style="color: #666666">=</span> <span style="color: #666666">@27</span>U;<br>    <span style="color: #008000; font-weight: bold">if</span> ([tuoiToi isEqualToNumber<span style="color: #666666">:</span> tuoiBanToi]) {<br>        NSLog(<span style="color: #BA2121">@&quot;Hai đứa tôi bằng tuổi&quot;</span>);<br>    } <br>    NSNumber <span style="color: #666666">*</span>tuoiCuaToi <span style="color: #666666">=</span> <span style="color: #666666">@20</span>;<br>    NSNumber <span style="color: #666666">*</span>tuoiCuaBanToi <span style="color: #666666">=</span> <span style="color: #666666">@30</span>;<br>    <span style="color: #008000; font-weight: bold">if</span> ([tuoiCuaToi compare<span style="color: #666666">:</span> tuoiCuaBanToi] <span style="color: #666666">==</span> NSOrderedDescending) {<br>        NSLog(<span style="color: #BA2121">@&quot;Tuổi của tôi lớn hơn tuổi bạn tôi&quot;</span>);<br>    } <span style="color: #008000; font-weight: bold">else</span> {<br>        NSLog(<span style="color: #BA2121">@&quot;Tuổi bạn tôi lớn hơn tuổi tôi&quot;</span>);<br>    } <br>}<br></pre>',
      'answer': '<pre style="margin: 0; line-height: 125%">Tuổi bạn tôi lớn hơn tuổi tôi </pre>',
      'time': 1.5
    }
  ],
}];

